server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: PROMOTIONSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.mr.boomsky_promotion_service.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
